### ISSUE TITLE
Continue menu not clickable + no selection laser in the menu

### ISSUE THREAD

**Issue by enarth** [Blueteak/QuiVrReporting#10]
Sometime, the continue button does not work...

I don't know exactly whant unblock the situation, but it's a conbination of drawing an arrow and going into the menu.
Btw, i realize that when the continue button bug, there are no selection laser in the menu

**Comment by andrewspode** [comment]
My experience in this situation is you just keep pulling your trigger over and over again and then it appears / clicks.

Some sort of haptic feedback on the continue button would let people know they haven't pressed it.

**Comment by Blueteak** [comment]
Should be fixed in 0.35.3
