### ISSUE TITLE
Disappearing bow

### ISSUE THREAD

**Issue by scientsit009** [Blueteak/QuiVrReporting#11]
I had my bow disappear and pressing rest bow and quiver didn't seem to do anything. I think the root of the problem was that my bow hand vive controller lost tracking or turned itself off. Leaving the multiplayer room fixed it until the controller was lost again.

**Comment by scientsit009** [comment]
http://steamcommunity.com/sharedfiles/filedetails/?id=855086852 screencap if it helphelps

**Comment by scientsit009** [comment]
Whatever happened losing tracking wasn't the problem the controller turned itself off. It just happened again at full battery but this time the bow respawned when the glove did.

**Comment by Blueteak** [comment]
Should be fixed in 0.35.9 with menu changes to hand activation/deactivation
