### ISSUE TITLE
Player data not finished loading until after game starts.

### ISSUE THREAD

**Issue by sagea** [Blueteak/QuiVrReporting#16]
When opening the game I see a blank leader board and none of my player data (Including emotes and player weapon/armor customization). The data then populates appears after about 2 seconds (Server Delay.)

Side Note:
During this time, I am unable to click any of the menu buttons to join single player or multiplayer (never tested the practice stage.)

**Comment by Blueteak** [comment]
This is due to the high server traffic on the weekend. It will be addressed on Tuesday when I upgrade the server to a higher capacity - more info [here](http://steamcommunity.com/games/489380/announcements/detail/246972234933804430).

**Comment by sagea** [comment]
Would it make sense to have the server request be apart of the loading screen? That way the data would exist before the player is placed in the tower.

**Comment by Blueteak** [comment]
It is, it's just actually taking that long at the moment when overloaded :(

**Comment by Blueteak** [comment]
Fixed after server update
