### ISSUE TITLE
Leader Board / Character Mannequin Still Rendering When Outside the Tower.

### ISSUE THREAD

**Issue by sagea** [Blueteak/QuiVrReporting#17]
While in the game, all of the UI and models are still being rendered. This can be seen from the tower shown in the link...
https://s24.postimg.org/6q0eg06ph/Tower_Data.jpg

**Comment by Blueteak** [comment]
I'm not sure that the image linked is the correct one (I can see a teleporter circled?), however I do understand the issue as it degrades performance.

An attempt was made earlier to fix this, but ended up sometimes hiding the mannequin/leaderboard/table when you teleported _into_ the tower and I felt it was better to be safe.

**Comment by Blueteak** [comment]
Static objects will now stop rendering after leaving tower (table, rug, etc), dynamic objects will continue to render though as creating Dynamic LOD/Culling is more processing power than letting them render. 

Implemented in 0.34.3
