### ISSUE TITLE
Crash on reforge

### ISSUE THREAD

**Issue by Nakano373** [Blueteak/QuiVrReporting#19]
Using an oculus, had it happen 2 out of 2 tries in the 0.34.1 patch (always worked fine previously). Pops up the "An crash dump has been created, it would be great if you would send this to the developer!" message and seems to screw up both steam and oculus (the second time it happend, steam wouldn't let me relaunch (kept saying the game was still running, even though it wasn't in the process list) and the Oculus app would relauch itself every time I tried to kill it. finally had to reboot to get everything back to normal.

[output_log.txt](https://github.com/Blueteak/QuiVrReporting/files/753323/output_log.txt)

[2017-02-05_125648.zip](https://github.com/Blueteak/QuiVrReporting/files/753324/2017-02-05_125648.zip)

**Comment by Blueteak** [comment]
New update (0.34.2) has a beta build available (instructions in patch notes [here](http://steamcommunity.com/games/489380/announcements/detail/246972234937716767)). 

Could you try it out and see if you get any red error logs on screen when you reforge?
