### ISSUE TITLE
Audio Output Change

### ISSUE THREAD

**Issue by andrewspode** [Blueteak/QuiVrReporting#2]
If I launch the game before SteamVR has had a chance to switch my audio source to USB (Vive) and then change the audio source, the game doesn't update to reflect this change. I will get audio in Steam Overlay, but not in the game.

I then have to quit the game and reload for it to reflect the change.

**Comment by Blueteak** [comment]
This is an issue with Unity (Editor functions the same way, if Editor is open before device is switched, it must be reloaded to refresh audio device).

The solution would be to implement an audio device selection panel in game, but that's a fairly significant system to implement for this issue.

**Comment by andrewspode** [comment]
It's not worth fixing - but could go on a "known issues" page just so it's acknowledged.
