### ISSUE TITLE
Arrows hitting own bow causing crashes

### ISSUE THREAD

**Issue by pcmccull** [Blueteak/QuiVrReporting#20]
I've seen this bug in several games this week and it has happened to me at least twice. When you look at another player who has this bug all of their arrows are just sticking into the bow where their hand is. So every time they shoot the arrow just hits their bow where their hand is on the bow. The two times this happened to me I couldn't see anything different it looked like the arrows were hitting their targets and the creatures were still falling, but other players said that I had arrows sticking out of my bow. One time after they said it, I tried to throw the time ball and it just hit an invisible wall in front of me. Both times the game crashed soon after this.

**Comment by Blueteak** [comment]
Arrows hitting other players' own bows will be fixed in the next update (0.34.4)

I think orb hitting invisible wall and crash are unrelated (welcome to create a new issue report for them)
