### ISSUE TITLE
Dead Minions lying around from previous game

### ISSUE THREAD

**Issue by g2-** [Blueteak/QuiVrReporting#24]
To reproduce this bug...
- MP game and had just killed boss and were at the End Game/Continue panel
- One of the players did not vote and game timed out.
- I had used a transport arrow to transport to the path at a spot near the top of the ramp just before the cave doors.

Issue #1 - 3 players had voted to continue but since one players did not vote we sat there and I assume there is a set time limit.  We hit that limit and the game did not continue. 
Expected > if majority votes to continue could just continue without waiting for remaining vote (I think that as soon as majority votes to end it ends even before all have voted)

Issue #2 - After that timed out game played two additional multiplayer games.  When I transported to the area where the boss had been killed in the first game the dead boss and a few dead minions were still visible from the first MP game.  I had even changed the group I played with after one of the games.  They finally went away when I played SP.  I can't recall if I only saw the dead minion objects when I transported to the same location, but I think so.

**Comment by Blueteak** [comment]
Have not seen any additional cases of this issue

Due to Continue Panel not being able to time out anymore (Auto-continue after 60 seconds), this should be fixed
