### ISSUE TITLE
Arcade Mode

### ISSUE THREAD

**Issue by g2-** [Blueteak/QuiVrReporting#27]
Probably known issues or features have just not been completed, but just in case...

#1 After changing to a profile the name above the tower dude is changed; however the equipment does not change to the profiles equipment.

#2 New items are awarded to the profile user following a game but no motes are saved.

**Comment by Blueteak** [comment]
1st issue fixed in previous patch

2nd issue fixed at some point in the past as many arcade users have motes saved in database
