### ISSUE TITLE
Continue menu interface

### ISSUE THREAD

**Issue by plusScooter** [Blueteak/QuiVrReporting#33]
Haven't noticed this reported but sometimes the lasers at the continue menu stay stuck on. Popping out to steam and back cleared them in the past but the last game was too intense after the continue to allow for that. Makes for some tricky aiming with lasers point in directions that you aren't shooting in.
Something to add to the whole continue menu thing :)

**Comment by Blueteak** [comment]
Should be fixed in 0.36.0
