### ISSUE TITLE
Target Area - After Top Score Game ID shown multiple times with others scores

### ISSUE THREAD

**Issue by g2-** [Blueteak/QuiVrReporting#35]
In the target area after you get a top score and keep playing the scoreboard displays your ID several times with scores that aren't associated with the ID.  If you leave and come back it will display it correctly.  This occurred in the regular release.  Did not experience the problem with top scores when I switched to the beta release.

**Comment by Blueteak** [comment]
With beta branch being accepted into current version, issue should be fixed.
