### ISSUE TITLE
Killed when transported to watchtower

### ISSUE THREAD

**Issue by plusScooter** [Blueteak/QuiVrReporting#38]
When a game has just finished, if you are standing on the right side gate(1st zone) when everyone gets transported back to the watchtower you will end up dead/ghosted probably due to the enemy that appears in that same spot just before the transport .

**Comment by Blueteak** [comment]
TODO: Postpone enemy spawn until 1-2 seconds after teleportation

**Comment by Blueteak** [comment]
Fixed
