### ISSUE TITLE
Blackscreen in multiplayer 

### ISSUE THREAD

**Issue by Jan-M-** [Blueteak/QuiVrReporting#42]
after approximately 5 minutes into the multiplayer my screen goes black and I hear enemy footsteps very loud. No HUD visible, all black, but the chaperone bounds still appear. Also it seems to be related to when something is happening at the gates. 

reinstalled and switched to beta. same error

**Comment by Blueteak** [comment]
This was due to a minor network disconnect not failing gracefully, fixed in 0.37.3b
