### ISSUE TITLE
Simultaneous gates destroyed and repaired

### ISSUE THREAD

**Issue by VRtuous-Ventures** [Blueteak/QuiVrReporting#47]
This doesn't happen often, but when it does it means you will probably lose within the next minute. If you happen to get a headshot and repair the gate that's further up at the same time the gate behind you is destroyed, you won't be able to reach the repaired gate ever again. It would be great if after you get pushed back and repair the gate that was just destroyed you jump straight to the furthest gate that is closed.

**Comment by plusScooter** [comment]
This happened today on the current build 38.97 defending zone 3 except 1 player teleported to the repaired z4 gate and one was sent to behind the broken gate in z2

**Comment by Blueteak** [comment]
Think this is now fixed due to new progression system
