### ISSUE TITLE
Bug Report: Game freezes (0.38.8)

### ISSUE THREAD

**Issue by IARI** [Blueteak/QuiVrReporting#53]
**What:**
The game freezes.
After a while the music stops, but some background sound loop keeps playing (Wind, or a closing gate, (which it happened once when i was about to close a gate))

**When:**
Happens at any place, no obvious particular event that triggers it (could be mob spawn or anything)
It also seems to happen independent of wave. I haven't noticed any clear factor that seem to correlate.

**output log** doesn't seem very helpful: [output_log.txt](https://github.com/Blueteak/QuiVrReporting/files/999850/output_log.txt)

Apologies for the spam:
I've already posted this on the steam forum and sent you via mail - but only just now discovered this repository, and figured that might actually be the best place for this.

**Comment by Blueteak** [comment]
Should be fixed now
