### ISSUE TITLE
[Feature Request] Fail Safe rewards

### ISSUE THREAD

**Issue by IARI** [Blueteak/QuiVrReporting#54]
With respect to #53 I would like to suggest a fail safe "progress backup" or at least "reward backup".

**Motivation:** My guess is, that the game will probably continue to evolve, and it might always be possible, that freezes or crashes will not occur.
With freezes or crashed comes a lot of player frustration: all progress and rewards are lost.

**Suggestion**
Make a fail safe backup of either
- the  pending rewards
- or even better: the game progress.
the first option is probably easier to implement, as it doesnt require saving that much additional data permanently.

**Comment by Blueteak** [comment]
Rewards are now all server-side so saving is never needed
