### ISSUE TITLE
MP: Other players floating

### ISSUE THREAD

**Issue by ThomasSmith3** [Blueteak/QuiVrReporting#6]
Sometimes in multiplayer fellow team mates are either floating above the current platform or below. They seem to be playing fine so must just be a sync error but wanted to let you know about it.

**Comment by Blueteak** [comment]
I'm assuming you mean the floating platforms in the fog area that move up/down. If so then yes, this is a sync issue where the floating platform positions aren't synchronized across the network.

**Comment by ThomasSmith3** [comment]
The platforms in the third area is where I was seeing this.

**Comment by Blueteak** [comment]
Removed floating platforms so closing issue
