### ISSUE TITLE
Flying mosters loop

### ISSUE THREAD

**Issue by ThomasSmith3** [Blueteak/QuiVrReporting#7]
When closing the last gate and the flying mosters spawn up near the ceiling when they start their flight they fly for a few second then do a loop de loop then carry on. This is not evertime one spawns there but maybe ever other one that spawns.

**Comment by Blueteak** [comment]
This is a known issue that has proven very difficult to track down the reason. Still working on it.

**Comment by Blueteak** [comment]
Fixed in 0.34.3
