### ISSUE TITLE
Monsters bashing gate at wrong position

### ISSUE THREAD

**Issue by andrewspode** [Blueteak/QuiVrReporting#8]
Teleporters are the worst affected by this, but often they will teleport and be nowhere near the gate, but start bashing anyway. Other times, enemies might only be a few feet away from the gate and start bashing. Frustrating when sometimes it happens and you can't even see the enemy that is killing your gate until it is too late.

**Comment by ScottMackay2** [comment]
It also seems like it is happening more often when the monsters start walking faster.

(This bug makes it almost impossible to stay alive at the higher levels where enemies bash the gate off in only 2 hits. Also this bug is already here from the beginning as far as I know. This really needs a fix.)

**Comment by plusScooter** [comment]
Might be a related data point but the teleporters will also sometimes start walking the opposite direction away from the gate.

**Comment by Blueteak** [comment]
Should be fixed now
